### ISSUE TITLE
Countdown badge?

### ISSUE THREAD

**Issue by orschiro** [denilsonsa/crx-reload-tab#3]
Hey @denilsonsa beautiful extension! :-D

If I set the timer to 20min, it shows 20 on the badge but doesn't actually count down. 

It would be nice if it could countdown so I can see directly how much time is left. 

What you think? .-)

**Comment by denilsonsa** [comment]
Hmm… Should I make that behavior configurable?

I'd like to, because updating the display every second uses a bit more CPU than "doing nothing at all". On the other hand, I suppose very few users will need this toggle, so I don't want to pollute the main popup UI.

I could create an "options" window, but that seems like overkill for one single option. I could add it to the context menu of the browser button, which might be the best idea so far.

**Comment by orschiro** [comment]
Hey. :-)

Thanks for considering my suggestion!

> I could add it to the context menu of the browser button, which might be the best idea so far.

How could that look like?

**Comment by denilsonsa** [comment]
I've finally got back to this. I've implemented an option available when right-clicking the extension button.

b39c98e8d0a17ca08ddede5d46a1f305d54d57ed
5b24bf0366a4c3b8d7c9d644acacc4ae856845a4

With these, I'm closing this feature request! Thanks!

**Comment by orschiro** [comment]
That's so cool, thank you! :-)
